version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kg_php
    working_dir: /srv/api
    volumes:
      - ./api:/srv/api:cached
    depends_on:
      - redis

  nginx:
    image: nginx:stable
    container_name: kg_nginx
    ports:
      - "8000:80"
    volumes:
      - ./api/public:/srv/api/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: kg_redis

  neo4j:
    image: neo4j:5
    container_name: kg_neo4j
    environment:
      - NEO4J_AUTH=neo4j/S3cur3P@ss
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  mercure:
    image: dunglas/mercure
    container_name: kg_mercure
    environment:
      - MERCURE_PUBLISHER_JWT_KEY=p0+9QkXl5ZfsR3VJqY2TqH8LtbIGb+8V6e+1L+5jZ0Y=
      - MERCURE_SUBSCRIBER_JWT_KEY=p0+9QkXl5ZfsR3VJqY2TqH8LtbIGb+8V6e+1L+5jZ0Y=
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=*
    ports:
      - "8001:80"

volumes:
  neo4j_data:
