version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: kg_php
    working_dir: /srv/api
    volumes:
      - ./api:/srv/api:cached
      - api_var:/srv/api/var
    depends_on:
      - redis
    command: >
      bash -c "
        chown -R www-data:www-data /srv/api/var &&
        chmod -R 770 /srv/api/var &&
        php-fpm
      "

  nginx:
    image: nginx:stable
    container_name: kg_nginx
    ports:
      - "8000:80"
    volumes:
      - ./api/public:/srv/api/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    container_name: kg_redis

  neo4j:
    image: neo4j:5
    container_name: kg_neo4j
    # if you want to use your logins, change the environment here, but if u want to push them, 
    # make it dynamic
    environment:
      - NEO4J_AUTH=neo4j/S3cur3P@ss 
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  mercure:
    image: dunglas/mercure
    container_name: kg_mercure
    environment:
      - DEBUG=1
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=*
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_PUBLISHER_JWT_KEY}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_SUBSCRIBER_JWT_KEY}
    ports:
      - "8001:80"

volumes:
  api_var:
  neo4j_data:
