api_platform:
    title: Hello API Platform
    version: 1.0.0
    graphql:
        enabled: true
        graphiql:
            enabled: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json:   ['application/json']
